### ISSUE TITLE
How can I get filename-sin/sout.graph?

### ISSUE THREAD

**Issue by RidgeSTD** [mutandon/Grava#2]
I've read your `eu.unitn.disi.db.exemplar.commands.TestExamplar.java` trying to understand how to load `Freebase` into memory to operate it. However, I saw the code directly use `filename-sin.graph` and `filename-sout.graph`, which makes me confused: **How can I get filename-sin/sout.graph?**

I know it's something basic in this field, but I don't get it. In the `Freebase data dump` I downloaded I see everything organized like:

```
<http://rdf.freebase.com/ns/american_football.football_player.footballdb_id> <http://rdf.freebase.com/ns/type.property.schema> <http://rdf.freebase.com/ns/american_football.football_player>   .
```

instead of `Long Long Long` format. Did you make some progress, like counting entities before?

---

And, did you use full freebase in the test of your paper _Exemplar Queries-Give me an Example of What You Need_? I found it REALLY BIG, up to 250G.

**Comment by mutandon** [comment]
The data dump from the website is in RDF format while we require triples of long obtained through a cleaning process that removes many useless information from the data graph (such as information about users, groups, schemas, etc ...). 
The two files are then the same file sorted by the first column (source) and by the second column (destination). So it is sorted by out-nodes and in-nodes respectively. 
Unfortunately, we didn't have much time to upload all of these things, but I can share with you a preliminary cleaning script to obtain both files. Many other information can be removed, though. 

We made progress on counting, but everything is under development and I currently don't have time to work on an optimized version of the library. In the near future probably we will have a more performing, less space consuming release. 

Let me clean up a bit the code, and I will upload the script, at least. 
You can use it on your dump.

**Comment by mutandon** [comment]
Please find the scripts in ExemplarQuery repository.
